package com.hrms.db.repositories.performance.interfaces;

import com.hrms.db.repositories.performance.models.Appraisal;
import java.util.List;

/**
 * IAppraisalRepository
 * Component: Appraisal & Review Component
 *
 * Stores and retrieves performance appraisal records and ratings.
 * DB Team must implement this interface and provide the concrete class.
 */
public interface IAppraisalRepository {

    /**
     * Create a new appraisal record with DRAFT status.
     * @param appraisal Appraisal object (appraisalId will be auto-generated by DB)
     * @return generated appraisalId on success, -1 on failure
     */
    int createAppraisal(Appraisal appraisal);

    /**
     * Mark an appraisal as SUBMITTED by the reviewer.
     * Also sets the submittedDate to current timestamp.
     * @param appraisalId appraisal to submit
     * @return true if submitted successfully, false otherwise
     */
    boolean submitAppraisal(int appraisalId);

    /**
     * HR or senior manager approves a submitted appraisal.
     * Sets status to APPROVED and records approverId and approvedDate.
     * @param appraisalId appraisal to approve
     * @param approverId  ID of the approving manager/HR
     * @return true if approved successfully, false otherwise
     */
    boolean approveAppraisal(int appraisalId, int approverId);

    /**
     * Fetch the appraisal for a specific employee in a specific cycle.
     * @param employeeId employee whose appraisal is needed
     * @param cycle      cycle string e.g. "2025-Annual"
     * @return Appraisal object, or null if not found
     */
    Appraisal getAppraisalByEmployee(int employeeId, String cycle);

    /**
     * Retrieve all past appraisals for an employee (all cycles).
     * @param employeeId employee whose history is needed
     * @return list of appraisals ordered by cycle descending; empty list if none
     */
    List<Appraisal> getAppraisalHistory(int employeeId);

    /**
     * Update the overall performance rating on an appraisal.
     * @param appraisalId appraisal to update
     * @param rating      new rating value (e.g. 1.0 to 5.0)
     * @return true if updated successfully, false otherwise
     */
    boolean updateRating(int appraisalId, float rating);
}
