package com.hrms.db.repositories.performance.interfaces;

import com.hrms.db.repositories.performance.models.AuditLog;
import java.util.Date;
import java.util.List;

/**
 * IAuditLogRepository
 * Component: Audit & Compliance Component
 *
 * Records all create/update/delete operations on performance data for audit trail.
 * DB Team must implement this interface and provide the concrete class.
 * NOTE: Audit logs must NEVER be deleted. Only append operations are allowed.
 */
public interface IAuditLogRepository {

    /**
     * Persist a new audit log entry.
     * Called by all other components whenever a data-modifying operation is performed.
     * @param log AuditLog object with all fields populated (logId auto-generated by DB)
     * @return true if logged successfully, false otherwise
     */
    boolean logAction(AuditLog log);

    /**
     * Fetch all audit logs for a specific entity (e.g. all changes to Goal #5).
     * @param entityType type of entity e.g. "Goal", "Appraisal", "KPI"
     * @param entityId   ID of the entity
     * @return list of AuditLog objects ordered by timestamp descending; empty list if none
     */
    List<AuditLog> getLogsByEntity(String entityType, int entityId);

    /**
     * Retrieve all actions performed by a specific user within a date range.
     * @param userId user whose actions are being audited
     * @param from   start date (inclusive)
     * @param to     end date (inclusive)
     * @return list of AuditLog objects in that range; empty list if none
     */
    List<AuditLog> getLogsByUser(int userId, Date from, Date to);

    /**
     * Return all audit events that occurred during a performance cycle.
     * @param cycleId the performance cycle
     * @return list of AuditLog objects for the cycle; empty list if none
     */
    List<AuditLog> getLogsByCycle(int cycleId);
}
