package com.hrms.db.repositories.performance.interfaces;

import com.hrms.db.repositories.performance.models.Goal;
import java.util.List;

/**
 * IGoalRepository
 * Component: Goal Setting & Tracking Component
 *
 * Handles persistence and retrieval of employee goals and OKRs.
 * DB Team must implement this interface and provide the concrete class.
 */
public interface IGoalRepository {

    /**
     * Persist a new goal record in the database.
     * @param goal Goal object (goalId will be auto-generated by DB)
     * @return generated goalId on success, -1 on failure
     */
    int createGoal(Goal goal);

    /**
     * Update an existing goal's details or progress.
     * @param goal Goal object with updated fields (goalId must be set)
     * @return true if updated successfully, false otherwise
     */
    boolean updateGoal(Goal goal);

    /**
     * Soft-delete a goal (sets is_deleted = true, does NOT remove from DB).
     * @param goalId ID of goal to delete
     * @return true if deleted successfully, false otherwise
     */
    boolean deleteGoal(int goalId);

    /**
     * Retrieve a single goal by its ID.
     * @param goalId unique goal identifier
     * @return Goal object, or null if not found or deleted
     */
    Goal getGoalById(int goalId);

    /**
     * Return all active (non-deleted) goals for an employee in a specific cycle.
     * @param employeeId employee whose goals are needed
     * @param cycle      cycle string e.g. "2025-Annual", "2025-Q2"
     * @return list of goals; empty list if none found
     */
    List<Goal> getGoalsByEmployee(int employeeId, String cycle);

    /**
     * Update only the progress percentage of a goal (0.0 to 100.0).
     * @param goalId   goal to update
     * @param progress new progress value (0.0 - 100.0)
     * @return true if updated successfully, false otherwise
     */
    boolean updateGoalProgress(int goalId, float progress);
}
