package com.hrms.db.repositories.performance.interfaces;

import com.hrms.db.repositories.performance.models.KPI;
import com.hrms.db.repositories.performance.models.KPIRecord;
import java.util.Date;
import java.util.List;

/**
 * IKPIRepository
 * Component: KPI Management Component
 *
 * Manages Key Performance Indicator definitions and recorded actual values.
 * DB Team must implement this interface and provide the concrete class.
 */
public interface IKPIRepository {

    /**
     * Create a new KPI definition in the database.
     * @param kpi KPI object (kpiId will be auto-generated by DB)
     * @return generated kpiId on success, -1 on failure
     */
    int createKPI(KPI kpi);

    /**
     * Link an existing KPI to an employee for a particular cycle.
     * @param kpiId      the KPI to assign
     * @param employeeId the employee to assign it to
     * @return true if assignment was successful, false otherwise
     */
    boolean assignKPIToEmployee(int kpiId, int employeeId);

    /**
     * Record an actual measured value for a KPI on a specific date.
     * @param kpiId  the KPI being measured
     * @param value  the actual measured value
     * @param date   the date of the measurement
     * @return true if recorded successfully, false otherwise
     */
    boolean recordKPIValue(int kpiId, double value, Date date);

    /**
     * Retrieve all KPIs assigned to an employee in a cycle.
     * @param employeeId employee whose KPIs are needed
     * @param cycle      cycle string e.g. "2025-Annual"
     * @return list of KPIs; empty list if none found
     */
    List<KPI> getKPIsByEmployee(int employeeId, String cycle);

    /**
     * Fetch the full historical record of measured values for a KPI.
     * @param kpiId KPI whose history is needed
     * @return list of KPIRecord objects ordered by date ascending; empty list if none
     */
    List<KPIRecord> getKPIHistory(int kpiId);
}
