package com.hrms.db.repositories.performance.interfaces;

import com.hrms.db.repositories.performance.models.Notification;
import com.hrms.db.repositories.performance.models.Reminder;
import java.util.Date;
import java.util.List;

/**
 * INotificationRepository
 * Component: Notification & Reminder Component
 *
 * Persists and retrieves system notifications and scheduled reminders.
 * DB Team must implement this interface and provide the concrete class.
 */
public interface INotificationRepository {

    /**
     * Store a new notification record in the database.
     * @param notification Notification object (notifId will be auto-generated by DB)
     * @return generated notifId on success, -1 on failure
     */
    int createNotification(Notification notification);

    /**
     * Mark a notification as read by the user.
     * @param notifId notification to mark as read
     * @return true if updated successfully, false otherwise
     */
    boolean markAsRead(int notifId);

    /**
     * Fetch all notifications (read and unread) for a specific user.
     * @param userId user whose notifications are needed
     * @return list of Notification objects ordered by createdAt descending; empty list if none
     */
    List<Notification> getNotificationsByUser(int userId);

    /**
     * Schedule a future reminder for a task/deadline.
     * @param reminder Reminder object with scheduledAt set to a future date
     * @return true if scheduled successfully, false otherwise
     */
    boolean scheduleReminder(Reminder reminder);

    /**
     * Retrieve all unsent reminders that are due on or before the given date.
     * Used by a background scheduler to dispatch reminders.
     * @param asOfDate reminders due up to and including this date
     * @return list of Reminder objects with sent = false; empty list if none
     */
    List<Reminder> getPendingReminders(Date asOfDate);
}
