package com.hrms.db.repositories.performance.interfaces;

import com.hrms.db.repositories.performance.models.PerformanceCycle;
import java.util.List;

/**
 * IPerformanceCycleRepository
 * Component: Performance Cycle Configuration Component
 *
 * Manages configuration of performance review cycles (annual, quarterly, etc.)
 * DB Team must implement this interface and provide the concrete class.
 */
public interface IPerformanceCycleRepository {

    /**
     * Create a new performance review cycle.
     * @param cycle PerformanceCycle object (cycleId will be auto-generated by DB)
     * @return generated cycleId on success, -1 on failure
     */
    int createCycle(PerformanceCycle cycle);

    /**
     * Fetch the currently active performance review cycle.
     * There should be at most one active cycle at a time.
     * @return the active PerformanceCycle, or null if none is active
     */
    PerformanceCycle getActiveCycle();

    /**
     * Retrieve a specific cycle by its ID.
     * @param cycleId unique cycle identifier
     * @return PerformanceCycle object, or null if not found
     */
    PerformanceCycle getCycleById(int cycleId);

    /**
     * List all performance cycles (past and present).
     * @return list of all PerformanceCycle objects ordered by startDate descending; empty list if none
     */
    List<PerformanceCycle> getAllCycles();

    /**
     * Mark a cycle as closed/completed (sets active = false).
     * @param cycleId cycle to close
     * @return true if closed successfully, false otherwise
     */
    boolean closeCycle(int cycleId);
}
