package com.hrms.db.entities;

import jakarta.persistence.*;

/**
 * File paths generated by payroll — payslips, challans, tax reports.
 */
@Entity
@Table(name = "file_references", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"emp_id", "pay_period"})
})
public class FileReference {

    @Id
    @Column(name = "ref_id", length = 36)
    private String refId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_id", nullable = false)
    private Employee employee;

    @Column(name = "pay_period", nullable = false, length = 10)
    private String payPeriod;

    @Column(name = "payslip_pdf_path", length = 500)
    private String payslipPdfPath;

    @Column(name = "pf_challan_path", length = 500)
    private String pfChallanPath;

    @Column(name = "tax_report_path", length = 500)
    private String taxReportPath;

    // --- Getters & Setters ---

    public String getRefId() { return refId; }
    public void setRefId(String refId) { this.refId = refId; }

    public Employee getEmployee() { return employee; }
    public void setEmployee(Employee employee) { this.employee = employee; }

    public String getPayPeriod() { return payPeriod; }
    public void setPayPeriod(String payPeriod) { this.payPeriod = payPeriod; }

    public String getPayslipPdfPath() { return payslipPdfPath; }
    public void setPayslipPdfPath(String payslipPdfPath) { this.payslipPdfPath = payslipPdfPath; }

    public String getPfChallanPath() { return pfChallanPath; }
    public void setPfChallanPath(String pfChallanPath) { this.pfChallanPath = pfChallanPath; }

    public String getTaxReportPath() { return taxReportPath; }
    public void setTaxReportPath(String taxReportPath) { this.taxReportPath = taxReportPath; }
}
