-- ============================================================
-- HRMS Central Database Schema
-- Engine: PostgreSQL (also compatible with MySQL/SQLite)
-- ============================================================

-- Core employee table — every subsystem reads this
CREATE TABLE employees (
    emp_id              VARCHAR(20)     PRIMARY KEY,
    name                VARCHAR(100)    NOT NULL,
    department          VARCHAR(100),
    grade_level         VARCHAR(20),
    basic_pay           DECIMAL(12,2),
    years_of_service    INTEGER         DEFAULT 0,
    role                VARCHAR(100),
    manager_id          VARCHAR(20)     REFERENCES employees(emp_id),
    employment_status   VARCHAR(20)     DEFAULT 'ACTIVE',  -- ACTIVE, INACTIVE, TERMINATED
    -- Tax / Multi-country fields (used by Payroll)
    country_code        VARCHAR(5),
    currency_code       VARCHAR(5),
    tax_regime          VARCHAR(50),
    state_name          VARCHAR(100),
    filing_status       VARCHAR(30),
    tax_code            VARCHAR(30),
    national_id_number  VARCHAR(50),
    created_at          TIMESTAMP       DEFAULT NOW(),
    updated_at          TIMESTAMP       DEFAULT NOW()
);

-- Attendance and leave hours per pay period (used by Payroll, Leave Mgmt, Time Tracking)
CREATE TABLE attendance (
    record_id               VARCHAR(36)     PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
    emp_id                  VARCHAR(20)     NOT NULL REFERENCES employees(emp_id),
    pay_period              VARCHAR(10)     NOT NULL,  -- e.g. '2024-06'
    working_days_in_month   INTEGER,
    leave_with_pay          INTEGER         DEFAULT 0,
    leave_without_pay       INTEGER         DEFAULT 0,
    hours_worked            DECIMAL(6,2)    DEFAULT 0,
    overtime_hours          DECIMAL(6,2)    DEFAULT 0,
    UNIQUE (emp_id, pay_period)
);

-- Financial inputs per pay period (used by Payroll, Expense, Benefits)
CREATE TABLE financials (
    record_id               VARCHAR(36)     PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
    emp_id                  VARCHAR(20)     NOT NULL REFERENCES employees(emp_id),
    pay_period              VARCHAR(10)     NOT NULL,
    pending_claims          DECIMAL(12,2)   DEFAULT 0,
    approved_reimbursement  DECIMAL(12,2)   DEFAULT 0,
    insurance_premium       DECIMAL(12,2)   DEFAULT 0,
    declared_investments    DECIMAL(12,2)   DEFAULT 0,
    UNIQUE (emp_id, pay_period)
);

-- Computed payroll outputs written back by Payroll subsystem
CREATE TABLE payroll_results (
    record_id               VARCHAR(36)     PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
    emp_id                  VARCHAR(20)     NOT NULL REFERENCES employees(emp_id),
    batch_id                VARCHAR(50)     NOT NULL,
    pay_period              VARCHAR(10)     NOT NULL,
    final_gross_pay         DECIMAL(12,2),
    final_net_pay           DECIMAL(12,2),
    penalty_amount          DECIMAL(12,2)   DEFAULT 0,
    pf_amount               DECIMAL(12,2)   DEFAULT 0,
    pt_amount               DECIMAL(12,2)   DEFAULT 0,
    monthly_tds_amount      DECIMAL(12,2)   DEFAULT 0,
    overtime_pay            DECIMAL(12,2)   DEFAULT 0,
    payout_amount           DECIMAL(12,2),
    reimbursement_payout    DECIMAL(12,2)   DEFAULT 0,
    gratuity_amount         DECIMAL(12,2)   DEFAULT 0,
    processed_at            TIMESTAMP       DEFAULT NOW(),
    UNIQUE (emp_id, batch_id, pay_period)
);

-- Audit log for payroll processing (errors + actions)
CREATE TABLE payroll_audit_log (
    log_id          VARCHAR(36)     PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
    batch_id        VARCHAR(50)     NOT NULL,
    emp_id          VARCHAR(20)     REFERENCES employees(emp_id),
    action_type     VARCHAR(50),    -- CALCULATE, SAVE, ERROR, etc.
    performed_by    VARCHAR(100),
    error_msg       TEXT,
    ts              TIMESTAMP       DEFAULT NOW()
);

-- File paths generated by payroll (payslips, challans, tax reports)
CREATE TABLE file_references (
    ref_id              VARCHAR(36)     PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
    emp_id              VARCHAR(20)     NOT NULL REFERENCES employees(emp_id),
    pay_period          VARCHAR(10)     NOT NULL,
    payslip_pdf_path    VARCHAR(500),
    pf_challan_path     VARCHAR(500),
    tax_report_path     VARCHAR(500),
    UNIQUE (emp_id, pay_period)
);

-- Leave records (used by Leave Mgmt, Expense, Payroll)
CREATE TABLE leave_records (
    leave_id        VARCHAR(36)     PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
    emp_id          VARCHAR(20)     NOT NULL REFERENCES employees(emp_id),
    start_date      DATE            NOT NULL,
    end_date        DATE            NOT NULL,
    leave_type      VARCHAR(30),    -- SICK, CASUAL, EARNED, UNPAID
    status          VARCHAR(20)     DEFAULT 'PENDING'  -- PENDING, APPROVED, REJECTED
);

-- Expense claims (used by Expense Mgmt subsystem)
CREATE TABLE expense_claims (
    claim_id        VARCHAR(36)     PRIMARY KEY DEFAULT gen_random_uuid()::varchar,
    emp_id          VARCHAR(20)     NOT NULL REFERENCES employees(emp_id),
    amount          DECIMAL(12,2)   NOT NULL,
    expense_date    DATE            NOT NULL,
    status          VARCHAR(20)     DEFAULT 'PENDING',
    approved_by     VARCHAR(20)     REFERENCES employees(emp_id),
    category_id     VARCHAR(20),
    created_at      TIMESTAMP       DEFAULT NOW()
);

-- ============================================================
-- Indexes for query performance
-- ============================================================
CREATE INDEX idx_attendance_emp_period ON attendance(emp_id, pay_period);
CREATE INDEX idx_payroll_results_batch ON payroll_results(batch_id);
CREATE INDEX idx_payroll_results_emp ON payroll_results(emp_id, pay_period);
CREATE INDEX idx_audit_log_batch ON payroll_audit_log(batch_id, emp_id);
CREATE INDEX idx_employees_status ON employees(employment_status);
CREATE INDEX idx_leave_emp ON leave_records(emp_id, start_date, end_date);
